swagger: "2.0"
info:
  description: "SecretSantaGenerator API Spec"
  version: "1.0.0"
  title: "SecretSantaGenerator API"
paths:
  /list:
    post:
      tags:
      - "list"
      summary: "Create a new santa list"
      description: ""
      operationId: "addList"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "405":
          description: "Invalid input"

    get:
      tags:
      - "list"
      responses:
        "404":
          description: "List not found"
